# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '002.ui'
#
# Created: Tue Jun 21 17:08:45 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(468, 409)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(468, 409))
        MainWindow.setMaximumSize(QtCore.QSize(468, 409))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.path_line = QtGui.QLineEdit(self.groupBox)
        self.path_line.setGeometry(QtCore.QRect(10, 20, 381, 20))
        self.path_line.setText(_fromUtf8(""))
        self.path_line.setObjectName(_fromUtf8("path_line"))
        self.fileDialogBtn = QtGui.QPushButton(self.groupBox)
        self.fileDialogBtn.setGeometry(QtCore.QRect(400, 20, 41, 21))
        self.fileDialogBtn.setObjectName(_fromUtf8("fileDialogBtn"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 451, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tage_line = QtGui.QLineEdit(self.groupBox_2)
        self.tage_line.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.tage_line.setObjectName(_fromUtf8("tage_line"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 451, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.num_line = QtGui.QLineEdit(self.groupBox_3)
        self.num_line.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.num_line.setObjectName(_fromUtf8("num_line"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 330, 451, 43))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.downloadBtn = QtGui.QPushButton(self.groupBox_4)
        self.downloadBtn.setEnabled(True)
        self.downloadBtn.setGeometry(QtCore.QRect(10, 10, 431, 23))
        self.downloadBtn.setObjectName(_fromUtf8("downloadBtn"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 70, 451, 131))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.CB_konachan = QtGui.QCheckBox(self.groupBox_5)
        self.CB_konachan.setGeometry(QtCore.QRect(10, 20, 90, 17))
        self.CB_konachan.setCheckable(True)
        self.CB_konachan.setChecked(True)
        self.CB_konachan.setObjectName(_fromUtf8("CB_konachan"))
        self.PB_konachan = QtGui.QProgressBar(self.groupBox_5)
        self.PB_konachan.setGeometry(QtCore.QRect(160, 20, 61, 16))
        self.PB_konachan.setProperty(_fromUtf8("value"), 0)
        self.PB_konachan.setTextVisible(False)
        self.PB_konachan.setInvertedAppearance(False)
        self.PB_konachan.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_konachan.setObjectName(_fromUtf8("PB_konachan"))
        self.PB_danboru = QtGui.QProgressBar(self.groupBox_5)
        self.PB_danboru.setGeometry(QtCore.QRect(160, 40, 61, 16))
        self.PB_danboru.setProperty(_fromUtf8("value"), 0)
        self.PB_danboru.setTextVisible(False)
        self.PB_danboru.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_danboru.setObjectName(_fromUtf8("PB_danboru"))
        self.CB_danboru = QtGui.QCheckBox(self.groupBox_5)
        self.CB_danboru.setGeometry(QtCore.QRect(10, 40, 140, 17))
        self.CB_danboru.setObjectName(_fromUtf8("CB_danboru"))
        self.PB_chan = QtGui.QProgressBar(self.groupBox_5)
        self.PB_chan.setGeometry(QtCore.QRect(160, 60, 61, 16))
        self.PB_chan.setProperty(_fromUtf8("value"), 0)
        self.PB_chan.setTextVisible(False)
        self.PB_chan.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_chan.setObjectName(_fromUtf8("PB_chan"))
        self.CB_chan = QtGui.QCheckBox(self.groupBox_5)
        self.CB_chan.setGeometry(QtCore.QRect(10, 60, 150, 17))
        self.CB_chan.setObjectName(_fromUtf8("CB_chan"))
        self.PB_idol = QtGui.QProgressBar(self.groupBox_5)
        self.PB_idol.setGeometry(QtCore.QRect(160, 80, 61, 16))
        self.PB_idol.setProperty(_fromUtf8("value"), 0)
        self.PB_idol.setTextVisible(False)
        self.PB_idol.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_idol.setObjectName(_fromUtf8("PB_idol"))
        self.CB_idol = QtGui.QCheckBox(self.groupBox_5)
        self.CB_idol.setGeometry(QtCore.QRect(10, 80, 150, 17))
        self.CB_idol.setObjectName(_fromUtf8("CB_idol"))
        self.PB_genso = QtGui.QProgressBar(self.groupBox_5)
        self.PB_genso.setGeometry(QtCore.QRect(160, 100, 61, 16))
        self.PB_genso.setProperty(_fromUtf8("value"), 0)
        self.PB_genso.setTextVisible(False)
        self.PB_genso.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_genso.setObjectName(_fromUtf8("PB_genso"))
        self.CB_genso = QtGui.QCheckBox(self.groupBox_5)
        self.CB_genso.setGeometry(QtCore.QRect(10, 100, 150, 17))
        self.CB_genso.setObjectName(_fromUtf8("CB_genso"))
        self.PB_oreno = QtGui.QProgressBar(self.groupBox_5)
        self.PB_oreno.setGeometry(QtCore.QRect(380, 20, 61, 16))
        self.PB_oreno.setProperty(_fromUtf8("value"), 0)
        self.PB_oreno.setTextVisible(False)
        self.PB_oreno.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_oreno.setObjectName(_fromUtf8("PB_oreno"))
        self.CB_oreno = QtGui.QCheckBox(self.groupBox_5)
        self.CB_oreno.setGeometry(QtCore.QRect(230, 20, 130, 17))
        self.CB_oreno.setObjectName(_fromUtf8("CB_oreno"))
        self.PB_behomini = QtGui.QProgressBar(self.groupBox_5)
        self.PB_behomini.setGeometry(QtCore.QRect(380, 40, 61, 16))
        self.PB_behomini.setProperty(_fromUtf8("value"), 0)
        self.PB_behomini.setTextVisible(False)
        self.PB_behomini.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_behomini.setObjectName(_fromUtf8("PB_behomini"))
        self.CB_behomini = QtGui.QCheckBox(self.groupBox_5)
        self.CB_behomini.setGeometry(QtCore.QRect(230, 40, 130, 17))
        self.CB_behomini.setObjectName(_fromUtf8("CB_behomini"))
        self.PB_gelbooru = QtGui.QProgressBar(self.groupBox_5)
        self.PB_gelbooru.setGeometry(QtCore.QRect(380, 60, 61, 16))
        self.PB_gelbooru.setProperty(_fromUtf8("value"), 0)
        self.PB_gelbooru.setTextVisible(False)
        self.PB_gelbooru.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_gelbooru.setObjectName(_fromUtf8("PB_gelbooru"))
        self.CB_gelbooru = QtGui.QCheckBox(self.groupBox_5)
        self.CB_gelbooru.setGeometry(QtCore.QRect(230, 60, 130, 17))
        self.CB_gelbooru.setObjectName(_fromUtf8("CB_gelbooru"))
        self.PB_nekobooru = QtGui.QProgressBar(self.groupBox_5)
        self.PB_nekobooru.setGeometry(QtCore.QRect(380, 80, 61, 16))
        self.PB_nekobooru.setProperty(_fromUtf8("value"), 0)
        self.PB_nekobooru.setTextVisible(False)
        self.PB_nekobooru.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_nekobooru.setObjectName(_fromUtf8("PB_nekobooru"))
        self.CB_nekobooru = QtGui.QCheckBox(self.groupBox_5)
        self.CB_nekobooru.setGeometry(QtCore.QRect(230, 80, 130, 17))
        self.CB_nekobooru.setObjectName(_fromUtf8("CB_nekobooru"))
        self.PB_animemahou = QtGui.QProgressBar(self.groupBox_5)
        self.PB_animemahou.setGeometry(QtCore.QRect(380, 100, 61, 16))
        self.PB_animemahou.setProperty(_fromUtf8("value"), 0)
        self.PB_animemahou.setTextVisible(False)
        self.PB_animemahou.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.PB_animemahou.setObjectName(_fromUtf8("PB_animemahou"))
        self.CB_animemahou = QtGui.QCheckBox(self.groupBox_5)
        self.CB_animemahou.setGeometry(QtCore.QRect(230, 100, 130, 17))
        self.CB_animemahou.setObjectName(_fromUtf8("CB_animemahou"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.ExitBtn = QtGui.QAction(MainWindow)
        self.ExitBtn.setObjectName(_fromUtf8("ExitBtn"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "img downloader", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Куда сохранять", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDialogBtn.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Теги", None, QtGui.QApplication.UnicodeUTF8))
        self.tage_line.setText(QtGui.QApplication.translate("MainWindow", "bakemonogatari", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Количество", None, QtGui.QApplication.UnicodeUTF8))
        self.num_line.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadBtn.setText(QtGui.QApplication.translate("MainWindow", "Скачать", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Выбрать сервисы", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_konachan.setText(QtGui.QApplication.translate("MainWindow", "Konachan.com", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_danboru.setText(QtGui.QApplication.translate("MainWindow", "Danbooru.donmai.us", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_chan.setText(QtGui.QApplication.translate("MainWindow", "Chan.sankakucomplex.com", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_idol.setText(QtGui.QApplication.translate("MainWindow", "Idol.sankakucomplex.com", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_genso.setText(QtGui.QApplication.translate("MainWindow", "Genso.ws", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_oreno.setText(QtGui.QApplication.translate("MainWindow", "Oreno.imouto.org", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_behomini.setText(QtGui.QApplication.translate("MainWindow", "Behoimi.org", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_gelbooru.setText(QtGui.QApplication.translate("MainWindow", "Gelbooru.com", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_nekobooru.setText(QtGui.QApplication.translate("MainWindow", "Nekobooru.net", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_animemahou.setText(QtGui.QApplication.translate("MainWindow", "Animemahou.com", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "Загрузить список файлов", None, QtGui.QApplication.UnicodeUTF8))
        self.ExitBtn.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.action_4.setText(QtGui.QApplication.translate("MainWindow", "Сохранить список", None, QtGui.QApplication.UnicodeUTF8))
        self.action_2.setText(QtGui.QApplication.translate("MainWindow", "О программе", None, QtGui.QApplication.UnicodeUTF8))
        self.action_3.setText(QtGui.QApplication.translate("MainWindow", "Справка", None, QtGui.QApplication.UnicodeUTF8))

